### ISSUE TITLE
Mitsuba 2?

### ISSUE THREAD

**Issue by amitibo** [mitsuba-renderer/mitsuba-data#1]
Hi,

Is there a planned release/timeline for the Mitsuba 2.0.0?

Thanks,
Amit

**Comment by wjakob** [comment]
Hi Amit,

this project is still unpublished, so we unfortunately can't make any promises as to when it might be released.

Best,
Wenzel

**Comment by ManishJu** [comment]
Any updates on when the project will be published ? The link on the official Mitsuba 2 website is broken : http://rgl.epfl.ch/publications/NimierDavidVicini2019Mitsuba2

**Comment by wjakob** [comment]
You will have to wait until Mid-November (around time time of SIGGRAPH Asia)

**Comment by erwincoumans** [comment]
SIGGRAPH Asia is on, the drums are rolling.

**Comment by wjakob** [comment]
We're still working on several important changes. Unfortunately that means we can't keep the originally planned timeline, there will be a delay of several weeks.

**Comment by lvjiahui** [comment]
Hi, wjakob
Will mitsuba2 released this year?
Thanks

**Comment by lvjiahui** [comment]
Hi, wjakob:

I'm very interested in your differentiable rendering work and can't wait to play with it. Will mitsuba2 released this year?

Thanks!

**Comment by Shreeyak** [comment]
I too would like to express my interest in Mitsuba 2. I am working on a new paper for detection of transparent objects. To create a training dataset, I'm looking to automate the rendering of ~50,000 images and have been directed towards Mitsuba as a method of achieving believable/accurate caustics.
Any rough timeline for release, @wjakob?

Also, wish you a happy new year!

**Comment by wjakob** [comment]
@Shreeyak, if your goal is just to render ordinary images, you will want to stick with Mitsuba 1. The main use cases of the new version are differentiable rendering and advanced physically-based rendering with polarization & color spectra. I won't give an exact release date given how far off I've been with my previous guesses, but things are looking fairly close to completion now. (probably a few more weeks)

**Comment by 3d-illusions** [comment]
Can  you let me know when mitsuba 2 gets released?  Want to share it to my group on facebook.  Or share it yourself if you like:

https://www.facebook.com/groups/Renderwars.xyz/

Looks awesome!

**Comment by el3ment** [comment]
Subscribing to this issue. Any other updates? I'm also very excited about Mitsuba 2 for it's differentiable rendering capacity.

**Comment by goddice** [comment]
Subscribing. Exciting.

**Comment by jenyav94** [comment]
Subscribing.

**Comment by merlinND** [comment]
Hi all,

Thanks a lot for your patience! We have released Mitsuba 2 today 🎉 
http://mitsuba-renderer.org/

**Comment by erwincoumans** [comment]
Congrats with the release! (first fork :-) )

**Comment by 3d-illusions** [comment]
Awesome!  Congrats.  

Now how do we get this bad boy into Blender :)

**Comment by goddice** [comment]
Nice and solid work!

**Comment by esx2ve** [comment]
Congrats 🥳
