### ISSUE TITLE
Conversion of Bitterli's scenes to mitsuba2+

### ISSUE THREAD

**Issue by bitinn** [mitsuba-renderer/mitsuba-data#13]
Hi,

I wonder how the team was able to convert [Bitterli](https://benedikt-bitterli.me/resources/)'s mitsuba 0.6 scene xml into 2.0 format? I assume a tool was developed to facilitate this conversion but couldn't find it in public.

Now that 3.0 is likely around the corner, I would love to know if this tool could be shared with community so we can compare mitsuba and pbrt more easily.

https://rgl.s3.eu-central-1.amazonaws.com/media/papers/NimierDavidVicini2019Mitsuba2_7.pdf
https://arxiv.org/pdf/2202.01284.pdf

Thanks in advanced!

**Comment by Speierers** [comment]
Hi @bitinn,

For the upcoming release, we have already converted all scenes from Bitterli's website which will be available to download online.

Converting those was partially automated but still required some manual tweaking an checking of the output scene. Hence I don't have a proper tool that can share at this point unfortunately.
