### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Vertexwahn** [mitsuba-renderer/mitsuba-data#15]
@Speierers Does [this License](https://github.com/mitsuba-renderer/mitsuba3/blob/master/LICENSE) also apply to this repository?

Can you please add a License here, so it is clear under what conditions this public repo can be used. Or is it only for private/internal use?

**Comment by wjakob** [comment]
I am not 100% sure about it, to be honest. Any code etc. produced by my group is open, but this repo also contains data/scenes created by others. I prefer not to have a license statement, which would be quite imposing on them.
